apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-portfolio
  template:
    metadata:
      labels:
        app: web-portfolio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - microboo
      containers:
      - name: nginx
        image: nginx:1.27.3-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
      initContainers:
      - name: git-clone
        image: alpine/git:v2.47.1
        args:
          - clone
          - --depth=1
          - https://github.com/shiv-tyagi/shiv-tyagi.github.io.git
          - /tmp/html
        volumeMounts:
        - name: html-content
          mountPath: /tmp/html
      volumes:
      - name: html-content
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web-portfolio-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-portfolio
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-portfolio
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "shiv.bigliboo.dev"
    - "www.bigliboo.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          namespace: default
          name: web-portfolio-service
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
